#!/bin/bash
#PBS -N "WRF_DMPAR_peppe"
#PBS -q reserved
#PBS_O_WORKDIR $rundir
#PBS -l nodes=8:ppn=10
#PBS -o host_out
#PBS -e host_err
#PBS -m abe
#PBS -M andrealuci82@gmail.com

# http://wiki.mpich.org/mpich/index.php/Using_the_Hydra_Process_Manager

#export num_proc=40
export HYDRA_DEBUG=1

cd $rundir

rm -f $rundir/rsl*
rm -f $rundir/host*

source /home/gdemarco/gfortran_wrf_enviroment_wrf34_mvapich2.sh

#set KMP_STACKSIZE=500000000
#set OMP_NUM_THREADS=8

ulimit -s unlimited

# info sulle opzioni mpiexec: sulla doc ufficiale
# http://www.mpich.org/static/downloads/3.1.3/mpich-3.1.3-userguide.pdf

#$MPI_ROOT/bin/mpiexec.hydra  
mpiexec --launcher ssh -iface ib0 -rmk pbs -print-all-exitcodes -wdir $rundir $rundir/wrf.exe 

#> qsub.log 2>&1
#--hostfile $rundir/machine_file
